### ISSUE TITLE
[T1] Problemas para correr selenium

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2513/Syllabus-S1-2024-1#10]
Hola, selenium no anda en el WSL de mi computador desde VSCode porque creo que instala versiones diferentes de Chrome y el driver de selenium de Chrome, quedándose pegado haciendo nada.
Qué debería hacer para que funcione?

**Comment by Mamunoz42** [comment]
Hola 😄!

Has intentado instalar selenium directamente en tu computador sin hacer uso de WSL?. Al ser una librería de Python no es necesario que estes trabajando con WSL.

Otra cosa importante es que selenium lo que hace es abrir este navegador y ejecutar las funciones que le indicaste en tú código, por lo que el inspeccionar la página se hace desde el navegador que tu utilices. Puedes revisar la issue #6.

Finalmente, si estás teniendo algún mensaje de error puedes enviar la foto de este para poder revisar con más claridad que es lo que realmente ocurre.

Quedo atento a cualquier cosa.
Saludos ✌🏽
