### ISSUE TITLE
[T1] Consulta BS4

### ISSUE THREAD

**Issue by KrishnaChaparro** [IIC2513/Syllabus-S1-2024-1#11]
Hola estoy confundida con lo que se debe hacer con beautiful soup 4 por que por lo que entiendo es para sacar los nombres de las classes o lo necesario del código html con eso. Yo lo hise con los deb tools por lo que no estoy segura si ese es el objetivo del bs4.

**Comment by Mamunoz42** [comment]
Hola 😄!

La idea de utilizar Bs4 es que una vez con selenium llegan a la página donde se encuentran los cursos solicitados, con Bs4 obtengan todos los cursos desplegados y puedan sacar la información solicitada. Y que esos resultados obtenidos se almacenen finalmente en un archivo `.csv`.

Recuerda que las DevTools las utilizamos para poder inspeccionar la página y así saber como interactuar con la página, para luego obtener la información requerida.

Espero haber contestado tu pregunta, de no ser así, no dudes en responder esta issue.

Saludos ✌🏽
