### ISSUE TITLE
[T1] Duda web scraping

### ISSUE THREAD

**Issue by Moisnt** [IIC2513/Syllabus-S1-2024-1#12]
Hola,
programando mi tarea por ahora abre una página que no tiene ninguna intervención previa (por ej los ramos que tenía para este semestre), por lo que me surgió la duda de si está bien así o deberia abrirse la página a la cual ya he intervenido antes. Lo pregunto para saber si necesito verificar que los campos de input no tengan algo escrito de antes o si está bien que se abra una página como lo hace por ahora.

**Comment by Mamunoz42** [comment]
Hola 😄!

Cuando haces uso de selenium debería abrirse la página que le indicas, para el caso de la tarea es la de inicio del buscacursos. Una vez ahí debes empezar a interactuar con la página.

La página no debería tener ningún input completado ni nada de información adicional a la que hay por defecto en esa página.

Saludos ✌️
