### ISSUE TITLE
[T1] Formato csv

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2513/Syllabus-S1-2024-1#13]
Buenasss, tengo una duda respecto al enunciado, no entiendo si las mayúsculas del ejemplo tienen que ir o solo es referencia, es decir, no entiendo si debe ser:

IIC3113;Gestión de Proyectos de Tecnologías de Información;Droguett Mario

o

IIC3113;GESTIÓN DE PROYECTOS DE TECNOLOGÍAS DE INFORMACIÓN;DROGUETT MARIO

Agradecido

**Comment by Mamunoz42** [comment]
Hola 😄!

Dejen los datos como los obtienen de la página de buscacursos, es decir, en este formato;

IIC3113;Gestión de Proyectos de Tecnologías de Información;Droguett Mario

Saludos ✌🏽!
