### ISSUE TITLE
[T1] Bug al seleccionar opción 2023 Primer Semestre

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#14]
Hola! Para trabajar con el drop down de opciones de semestres, usé Select de Selenium. Sin embargo luego de seleccionar 2023 Primer semestre se me cae el programa. Puedo notar que si encuentra el elemento y lo cambia exitosamente, pero justo después se cae. El mensaje adjunto es  Message: stale element reference: stale element not found. Leer la parte de errores de la documentación no me ayudó mucho, puesto a que casi todas las soluciones asumían que el elemento no había sido reconocido o no existía, mientras que en mi caso si puedo cambiar el valor de opción exitosamente. Alguna idea de por qué me ocurre esto?

**Comment by TTrincado** [comment]
Ya lo solucioné :)! Curiosamente debía reestructurar el código y aplicar una estrategia de espera implícita, debido que al cambiar de opción en el drop down la página se "resettea" y los inputs se limpian.

**Comment by nanglada** [comment]
Súper! Que bueno que lo hayas podido solucionar. Mucha suerte :)
