### ISSUE TITLE
[T1] Duda sobe repetición de cursos en el .csv

### ISSUE THREAD

**Issue by gabo1243** [IIC2513/Syllabus-S1-2024-1#15]
Hola, estaba viendo los cursos a guardar en el .csv y hay algunos que se dictan en secciones distintas como IIC3113. En este caso ¿dejo ambas secciones por separado o agrupo todo en una sola linea y junto profesores?

opción 1:
IIC3113; .... ; Profesor 1
IIC3113; .... ; Profesor 2

opción 2:
IIC3113; ....; Profesor 1, Profesor 2

**Comment by nanglada** [comment]
Hola! Podrías dejarlo de cualquier forma con tal de que lo especifiques en el README. Sin embargo, recomiendo no complicarse y dejarlo como la opción 1 nomás. 
Mucha suerte :)
