### ISSUE TITLE
Error con un componente de react

### ISSUE THREAD

**Issue by Javipipi** [IIC2513/Syllabus-S1-2024-1#150]
Hola!, perdón la hora pero recién mi página me está tirando este error ''/src/components/Button/Button.jsx?t=1712962729786' does not provide an export named 'ButtonComponent' (at ProductCard.jsx:5:9)' y no entiendo por qué, ya que en la carpeta Button yo tengo un archivo llamado Button que tiene un componente llamado ButtonComponent y al final se este lo tengo con 'export default ButtonComponent'. Empezó a tirarme este error recién ahora, el componente lo creé hace varias horas y funcionaba, salí un rato y cuando volví a correr la página dejó de funcionar.

**Comment by rodrigoogalde** [comment]
Hola!
Recuerda usar los "../../" dependiendo en donde se encuentren tus componentes y desde donde lo estes importando
Por ejemplo:
```
|
|-components/
  |-- componente1
|-vistas/
  |-- vista1
```
Para este ejemplo deberia ser
`import Componente1 from '../components/componente1'; `

**Comment by Javipipi** [comment]
No era ese el problema, estaba bien definido el path, el problema eran unas llaves. Igual graciass
