### ISSUE TITLE
[T1] Encoding de BS4

### ISSUE THREAD

**Issue by nicoschwend** [IIC2513/Syllabus-S1-2024-1#16]
Logro obtener todos los datos de los cursos, pero los caracteres especiales de español los tira con simbolo ?. probé distintos encodings y sigue lanzandolos igual. Que solución recomiendan para esto?

**Comment by Mamunoz42** [comment]
Hola 😄!

Me parece raro que estés teniendo problemas con los encoding, sin embargo, como la tarea no tiene un enfoque en como escriben la información, sino en como la obtienen, no te preocupes con esto mientras la información que estés obteniendo sea la correcta y cumpla con el formato que se solicita en el enunciado.

Saludos ✌🏽
