### ISSUE TITLE
[T3] Problema con koa-body

### ISSUE THREAD

**Issue by andrius6789** [IIC2513/Syllabus-S1-2024-1#173]
Al iniciar el proyecto si realizaba npm run dev en tarea-3.../backend obtenia un error critico con el estado de koa body y para solucionarlo me ofrecia utilizar el commando

npm audit fix --force

Al correr cambio la version de este a una version mas antigua y compatible y segui realizando el proyecto. El tema es que ahora al realizar npm run dev en mi backend obtengo el siguiente error

![image](https://github.com/IIC2513/Syllabus-S1/assets/62076980/6d0e981f-f287-4f8b-b65f-03e903a7b915)

Por sugerencia de chatgpt al explicarle li problema me sugirio desinstalarlo y volver a instalarlo por lo que lo hice pero al intentar instalarlo nuevamente me surgio el mismo problema que tenia al principio con la misma solucion que era forzar una version anterior:

![image](https://github.com/IIC2513/Syllabus-S1/assets/62076980/be2cbf3b-4b12-4042-a6e7-a07d5ebfef68)

Siento que quizás es algo muy especifico pero llevo mucho rato intentando solucionar esto y no se como proceder, gracias.

**Comment by ChumiColores** [comment]
Antes que cualquier otra cosa, me confirmas que instalaste los módulos usando `yarn` desde la carpeta en que está el archivo package.json y que tampoco te funciona si lo ejecutas con yarn dev? Dudo que esto último sea el problema, pero para descartar lo más sencillo

**Comment by andrius6789** [comment]
Hola si utilice yarn install para empezar el proyecto y luego lo ejecute con yarn dev de igual forma. Por alguna razon sin tener que haber forzado el cambio de version como lo habia hecho anteriormente al reiniciar el pc ya no existia este error. Gracias
