### ISSUE TITLE
[T3] Problema con DELETE y PATCH de modelos creados con seed

### ISSUE THREAD

**Issue by andrius6789** [IIC2513/Syllabus-S1-2024-1#175]
buenas, puedo realizar gets, post, patchs y deletes de objetos creados en la pagina de localhost.../Entries/User para los 3 users que he creado con seed pero para ninguno de los 3 he podido eliminar o patchear con los iconos de la pagina en el navegador los 2 objetos inciciales del seed mientras que los creados por mi a traves de esa pagina si. Cuando veo los errores en consola me dice que intento hacer DELETE del localhost:3000/entries/null con status 400 (de mi ruta)

Entonces me queda la duda de si es por la forma en la que se generan los recursos del frontend u otra cosa, cabe destacar que revise mi codigo del seed y del modelo de entries para asegurarme de que el id fuera creado.

Por otro lado, cuando accedo a la db con sudo -u username -d db_tarea3 e intento hacer \dt para ver las tablas no me sale nada lo cual me parece muy raro porque cuando utilizo el front para crear algo con los iconos se crea y me sale la informacion en la consola que tengo corriendo backend

**Comment by ChumiColores** [comment]
Antes que todo es importante que puedas acceder a las tablas que has creado. Así puedes debuguear eficazmente. Por mi parte, accedo de esta manera a la tabla, ve si te funciona
![imagen](https://github.com/IIC2513/Syllabus-S1/assets/101197947/bc56013a-3c4f-4489-a590-715f21cbfc68)

Ya con eso se puede empezar a ver tu problema con los usuarios que tú creas, para ver que efectivamente los estás creando o qué otro problema puede ser. 

Sobre que te salga que se hace DELETE sin ninguna interacción estoy clueless. Veamos los otros problemas primero.

**Comment by andrius6789** [comment]
Hola, descubri que existia la bd de development debugeando y lo pude solucionar de ahi gracias. El error tenia que ver con la forma en la que se creaba el modelo, editando el modelo me equivoque y le puse 2 veces id de distinta forma sin borrar el anterior. Gracias!
