### ISSUE TITLE
[T3] consultan funcionan en back y no front

### ISSUE THREAD

**Issue by solebravo** [IIC2513/Syllabus-S1-2024-1#183]
Hola, puede que este problema venga de algo que no entiendo, pero me pasa que cuando pruebo por ejemplo el metodo post user.create en postman me crea un nuevo usario sin problemas, pero si lo ingreso en la casilla del frontend no se crea, solo pasa a la siguiente pantalla, pero no lo veo reflejado en la bdd, por ejemplo en postman. No se si es que estoy entiendiendo algo mal o es un error.
Saludos!

**Comment by solebravo** [comment]
Hola, no caché como borrar la issue, pero se soluciono, creo que estaba medio lento nomas

**Comment by cristobalmujicap** [comment]
Hola, ya logré hacer todas las consultas en postman pero no logro conectar el back con el front. Cambié la URL del frontend así:
const URL_BACK='http://localhost:3000/';
Después corro yarn dev en distintas carpetas de la terminal, pero no se logran conectar. ¿Alguien sabe como solucionarlo?
