### ISSUE TITLE
Duda respecto a figma

### ISSUE THREAD

**Issue by ComPups** [IIC2513/Syllabus-S1-2024-1#21]
Hola! Leí en el enunciado que no se pueden usar bibliotecas de componentes y quería saber si podíamos usar Figma para prototipar y posteriormente exportar código CSS y HTML. 
Saludos

**Comment by nanglada** [comment]
Hola! Figma no está prohibido en sí, pero si recomendamos fuertemente que lo usen solo desde la entrega 2 en adelante para que puedan aprovechar esta E1 para aprender CSS lo mejor posible. Igualmente, si deciden usar Figma, recuerden que deben referenciar exactamente en que parte de su código fue utilizado.
