### ISSUE TITLE
Error: Could not resolve "react"

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#22]
Hola! Probando las cosas de la cápsula me tira este error al intentar conectar las routes, específicamente en al conectar react-router-dom. Tengo una versión más antigua de react debido a que la descargé hace unos meses, pero no logro resolverlo. Algún tip? Adjunto foto del problema. 
![Captura de pantalla 2023-09-08 a la(s) 20 44 53](https://github.com/IIC2513/Syllabus-S1/assets/101355363/b48efbb8-85f1-4120-af9a-ccdf722f2292)

**Comment by rodrigoogalde** [comment]
Borra `package-lock.json` y `yarn.lock`
Busca en la carpeta `node_modules` si existe la carpeta `react`, en el caso de que no, agregalo a tu `package.json`

Después corre `yarn install` y verifica si se creó la carpeta de `react` en `node_modules`

**Comment by TTrincado** [comment]
Muchas gracias!
