### ISSUE TITLE
Duda librerias permitidas

### ISSUE THREAD

**Issue by sofbriseno** [IIC2513/Syllabus-S1-2024-1#23]
Hola!
Tengo una duda respecto a las librerías permitidas... se puede usar la librería React Spring?

**Comment by Moisnt** [comment]
Hola, me sumo a esta pregunta para saber si puedo usar styled-components

**Comment by nanglada** [comment]
Hola! Para esta entrega, la idea es que se manejen con puro React y CSS, por lo que no está permitido ni React Spring, ni styled-components. Desde la E2 en adelante podrán usar ambos!
Éxito ⭐
