### ISSUE TITLE
[T2] Error 500 GET /products

### ISSUE THREAD

**Issue by scagender** [IIC2513/Syllabus-S1-2024-1#25]
Creo tener un problema con el mensaje que deberia obtener del error en la parte de GET /products. En GET /products/{id} no tuve problemas para obtener el mensaje "error" del json, pero en esta parte no lo puedo obtener, y tampoco lo encuentro buscando a mano en la consola con el console.log(error).

**Comment by rodrigoogalde** [comment]
Hola!
No estoy seguro si entiendo bien tu pregunta, pero me parece que te falta hacer un catch del error
Si me puedes explicar un poco más te puedo dar más detalles!
