### ISSUE TITLE
[T2] Get Category - IDs

### ISSUE THREAD

**Issue by SkylerEverett** [IIC2513/Syllabus-S1-2024-1#26]
¡Hola!

Completé la vista para el endpoint de getcategory, sin embargo, quería preguntar si es que debemos asumir que pondrán IDs de las catergorías correspondientes de forma correcta, ya que de otra manera no se completa nada y arroja un error de `Not Found` en consola.

De paso, me gustaría preguntar si en la primera parte, al obtener todos los productos, basta con solo los nombres o debe ser toda la información de cada producto.

Gracias desde ya :)

**Comment by nanglada** [comment]
Hola! 😊

Sobre lo primero, la idea es que tu conectes el endpoint tal que funcione con los casos adecuados (ósea el ID con la categoría apropiada). No te preocupes con que salga el Not Found.

Sobre lo segundo, queda a criterio suyo. Sin embargo, recomiendo poner toda la información del producto en caso de que haya nombres de productos repetidos. 

Éxito con la tarea ⭐️

**Comment by SkylerEverett** [comment]
Gracias ✨
