### ISSUE TITLE
[T2] Conexión api

### ISSUE THREAD

**Issue by ViceRet** [IIC2513/Syllabus-S1-2024-1#27]
hola, hace rato que estoy tratando de conectarme con la api pero no recibo nada, al mirar la consola me devuelve "Access to fetch at 'http://54.166.215.100:3000/docs/' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." ojalá me puedan ayudar

**Comment by rodrigoogalde** [comment]
Hola!
Para conectarte a la API, tiene que usar `http://54.166.215.100:3000/`
Al colocar `/docs` en el endpoint (al final de la URL) estas accediendo a la documentación

Si quieres obtener datos de la API, deber usar el URL y el endpoint a consultar (leer la documentación de los endpoints disponibles)
