### ISSUE TITLE
[T2] Problemas con mostrar info en GET

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2513/Syllabus-S1-2024-1#28]
Buenas, en la primera parte de la tarea logro hacer la consulta y todo bien con los datos que se piden pero no he logrado poder mostrarlos. Si entiendo bien, handleClickGet es una variable¿ por lo que no me hace mucho sentido retornar algo (lo he intentado igual pero nada jsjs) no sé si se puede pedir una guía sobre cómo interpretar al menos esa función/variable para saber como pasar esa info a algún componente

Graciasss

**Comment by rodrigoogalde** [comment]
Holaa!
La función `handleClickGet` tiene como fin hacer la consulta al endpoint, en este caso `/products`.
La función no necesita retornar nada, pero para poder guardar lo que te retorna puedes usar un `useState`  en el formato que te salga más cómodo (por ejemplo una lista) y luego con eso puedes hacer un mapeo de los datos
Avisame si no te queda claro
Que estes bien!

**Comment by AlfonsoBadilla** [comment]
Clarísimo, no lo había pensado
Ya funcionando, muchas gracias 🫱🏿‍🫲🏿
