### ISSUE TITLE
[T2] ID al agregar un producto

### ISSUE THREAD

**Issue by isidoraabumohors** [IIC2513/Syllabus-S1-2024-1#29]
Hola,

Me queda una duda respecto a cuando agregamos un producto con el método POST. Al pedir los datos, no se solicita un id, pero luego, para revisar si el producto fue creado, se nos pide un id. En este sentido, nosotros debemos escoger un id arbitrario? Para tal caso, cómo se tendría que hacer para que no se repitiera y para que la persona que rellenó el formulario del POST luego pueda verificar si se agregó el producto en el formulario que sigue, lo que requiere un ID?

Gracias!

**Comment by rodrigoogalde** [comment]
Hola!

2 cosas:

1. Si revisas la [documentación](http://54.166.215.100:3000/docs/), podrás ver que el método POST no requiere de un ID, ya que este se agrega de forma automática al realizar un POST.
2. La gracia del input ID, es que luego de que hayas hecho el POST, puedas verificar que se creó correctamente, ya que al hacer un POST, este te retorna el ID del nuevo producto agregado. Entonces con es ID, puedes hacer el GET y verificar que se creó correctamente

Avísame si no te queda claro

Saludos!

**Comment by isidoraabumohors** [comment]
Perfecto gracias!

**Comment by isidoraabumohors** [comment]
Hola! 

Me sigue quedando una duda sobre el ID. Tenemos que mostrar el ID en la pantalla, avisando que se creó correctamente el producto y mostrando el ID que se le asignó? Esto para que luego en la siguiente página podamos revisar, de acuerdo a ese id, si se creó correctamente? O podemos asumir que para revisarlo van a ver el ID impreso en la consola y no es necesario implementar un mensaje en la pantalla? Espero se entienda mi duda.

Gracias!

**Comment by rodrigoogalde** [comment]
Hola!

No es necesario que muestren el ID en la pantalla, con solo implementar la función esta super. Al final el input de ID nos sirve para comprobar si tu función creó correctamente  el producto. O con imprimirlo también sirve para comprobar que tuviste un response 200

Cualquier duda me avisas

Saludos!!
