### ISSUE TITLE
[T1] Duda sobre orden de ramos en el csv

### ISSUE THREAD

**Issue by gabo1243** [IIC2513/Syllabus-S1-2024-1#3]
Hola, cuando ya obtengo los ramos y sus datos, ¿debo dejarlos en el mismo orden que aparecen en el buscacursos o da lo mismo (en el archivo csv)?

Gracias de antemano.

**Comment by Mamunoz42** [comment]
Holaa, el orden de los ramos dentro del `.csv` no es importante. Lo que importa es que entregues la información solicitada para cada uno de los ramos.

Saludos 😄
