### ISSUE TITLE
[T2] Duda código base y css

### ISSUE THREAD

**Issue by FGarciaVarela** [IIC2513/Syllabus-S1-2024-1#31]
Hola! Quería preguntar si se espera que hagamos la parte de frontend y back de la app, o que trabajemos solo back desde el frontend que ya viene? Aprovecho de preguntar si adecuemos el css también para la página (que el código base no permite ver bien algunas cosas).

De antemano muchas gracias y que estés muy bien!

**Comment by nanglada** [comment]
Hola! Dado que no solo les pedimos conectarse con la API, no hay trabajo de back que hacer (las conexiones se hacen en el front) así que no te preocupes con trabajar con nada más que con lo que les entregamos. Ahora, sobre el css, tienen libertad de cambiarlo, pero no debería ser necesario. 
Éxito con la tarea ⭐️
