### ISSUE TITLE
[T2] Duda en las páginas de GET

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2513/Syllabus-S1-2024-1#32]
Buenas, en el enunciado dice que debemos ser capaces de buscar productos por ID y por ID + categoria, esas dos cosas deberían hacerse en el archivo GetCategoryPage? 

Graciasss

**Comment by nanglada** [comment]
Hola! Buscar productos por ID está implementado en la última parte, en la sección de DELETE. Ahí podrás encontrar un botón borrar y un botón "GET". Te recomiendo revisar la documentación del template que les dimos, ahí se explica más en detalle. Por lo tanto, la parte de ID + categoría es lo único que tiene que tener GetCategoryPage. 

Ojalá con esto te quede más claro. 
Éxito en la tarea ⭐️
