### ISSUE TITLE
[T2] Método PUT

### ISSUE THREAD

**Issue by isidoraabumohors** [IIC2513/Syllabus-S1-2024-1#33]
Hola!

Tengo una duda sobre la implementación del método PUT. Al navegar por la página, se llega a esta ruta después de POST y sale un botón de revisar si se creó, aparte de un formulario que pide todos los atributos del producto. La idea es escribir todos los datos del producto que se creó con el método POST en la página anterior, usando los atributos que se ingresaron manualmente en esta página anterior, más el ID que le agregó la API (y que tendríamos que imprimr en consola para poder verlo)? Si ese es el caso, no sé por qué sería un método PUT ya que al revisar si un producto se creó no lo estaríamos modificando (solo hariamos un GET). Además, la idea del botón submit es que haga un PUT? A pesar que el form pide todos los datos y según la documentación el método PUT solo recibe el id del producto (no los otros atributos para modificar).

En resumen, no entiendo bien que se espera que hagamos al apretar los botones de submit y de revisar si se creó. Además, no entiendo qué atributos se quieren modificar para implementar el método PUT.

Espero me puedan aclarar! Gracias de antemano.

**Comment by nanglada** [comment]
Hola! 

Primero que todo, te recomiendo revisar bien la documentación de la API ya que le método PUT no solo recibe id, sino que tiene que tener un body asociado. La idea es que tu pongas el ID de algún producto existente, rellenes el formulario con los nuevos datos del producto y al hacerle click, lo puedas actualizar utilizando el PUT. El botón "revisar si se creó" es para que puedas verificar que lo que hiciste con este endpoint efectivamente funcionó. 

Ojalá te quede más claro ahora. 
Éxito con la tarea ⭐️
