### ISSUE TITLE
[T2] Presentación datos Get Products

### ISSUE THREAD

**Issue by AndrewVenegas** [IIC2513/Syllabus-S1-2024-1#34]
Hola!

Tengo una consulta, qué hay que mostrar al hacer Get products. ¿Basta con el id y el nombre de cada producto? O debemos mostrar todos los atributos de cada producto? 

Y quería confirmar, el formato de presentación de los productos es libre (tabla, texto, listado, etc)?

Saludos!

**Comment by nanglada** [comment]
Hola! Sobre lo primero, queda a criterio que es lo que tienen que mostrar. Recomiendo que no sea el puro nombre en caso de que hayan productos repetidos, pero si es solo ID y nombre o todos los datos, pueden decidirlo ustedes. Y sí, el formato es libre, presenten los datos de la forma en la que consideren apropiada. 
Éxito con la tarea ⭐️

**Comment by AndrewVenegas** [comment]
Graciaas!!
