### ISSUE TITLE
[T2] Uso del token

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2513/Syllabus-S1-2024-1#35]
Hola! Cómo se usa el token para modificar datos/Cómo puedo averiguar cómo usarlo? Perdonen si es muy obvio.

**Comment by rodrigoogalde** [comment]
Hola!
Te recomiendo leer esta documentación
https://swagger.io/docs/specification/authentication/bearer-authentication/

Suerte en la tarea!

**Comment by NicoJGutierrez** [comment]
Muchas gracias! Ahí me funcionó cuando le puse el token en el header a mi request.
