### ISSUE TITLE
[E2] Cápsula extra

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2513/Syllabus-S1-2024-1#37]
Hola!

No entiendo muy bien en qué orden se realizan los videos agregando la cápsula extra. ¿La cápsula extra se haría antes de la cápsula 10 (sequelize + diagrama E/R) o después?

Gracias!

**Comment by nanglada** [comment]
Hola! La idea es que tengan Postgres instalado y configurado bien cuando empiecen a usar Sequelize así que recomiendo que vean esta cápsula extra antes. 
Suerte!
