### ISSUE TITLE
[E2] Error al correr yarn sequelize-cli db:migrate

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#38]
Cuando corro esto me sale este peculiar error 
![Screenshot 2023-10-22 at 14 25 37](https://github.com/IIC2513/Syllabus-S1/assets/101355363/dee1b326-de9c-42ab-a254-17553ebd53a4)
Sin embargo al cambiar "type": "commonjs" en el package.json me devuelve el error a la inversa 
![Screenshot 2023-10-22 at 14 31 08](https://github.com/IIC2513/Syllabus-S1/assets/101355363/419886a8-167d-411a-9155-54ab2a312403)

Alguna idea de por qué?

**Comment by rodrigoogalde** [comment]
Hola!
Recuerda que si utilizas `type: commonjs` para importar archivos, tienes que utilizar esta forma de importar:
`const Router = require('koa-router');`
Si utilizas `type: module`, tienes que importar así:
`import defaultExport from "module-name";`

Si no lo habías notado, en una de las cápsulas se saltan esta parte (cambiar la forma de importar) y cambian todos los archivos a la primera forma. Probablemente tu problema va porque tiene ambas formas de importar.

**Comment by TTrincado** [comment]
Era eso mismo! Muchas gracias :).
