### ISSUE TITLE
[E2] Acceso base de datos psql

### ISSUE THREAD

**Issue by aedwardsg** [IIC2513/Syllabus-S1-2024-1#39]
Hola! ¿Cómo se puede acceder a la base de datos de psql si la tiene otra integrante de mi grupo y en mi computador no existe? Debo crear la base de datos de nuevo? O hay alguna forma en que pueda acceder a la de mi compañera?
Gracias

**Comment by Mamunoz42** [comment]
Hola 😄!

Cuando se trabaja sobre proyectos que utilizan bases de datos estas siempre se crearán de forma local, por lo que cada persona que quiera trabajar sobre este proyecto o probarlo deberá crear la base de datos donde se guardará la información del proyecto.

Para poder llevar a cabo este proceso `sequelize-cli` y la utilización de variables de entorno nos serán de gran ayuda.

Como habrán visto en la cápsula [10](https://youtu.be/bZ__u-G-uqQ?si=jaBUWEgQkDmggp-p) (si no la han visto es importante que la revisen), se define un archivo `config.js`, el cual se utiliza para configurar la base de datos que se utilizará en el proyecto. Dentro de esta se deben definir una serie de variables, las cuales definen lo siguiente:

- **username**: Nos indica con que usuario crearemos la base de datos. Este valor debería ser algún usuario que tengan creado en Postgres o podrían usar postgres por defecto.
- **password**: La contraseña para ingresar con ese usuario a Postgres.
- **database**: El nombre que le quieren dar a la base de datos.
- **host**:  Corresponde a donde va a estar hosteada la base de datos, en general siempre será el localhost.
- **dialect**: Corresponde al motor de base de datos a utilizar, en nuestro caso es `postgres`.

Teniendo claridad con que representa esto, nosotros tendremos que replicar lo que aparece en la cápsula, es decir, utilizar un archivo `.env` para definir las variables de entorno de su proyecto, archivo el cual deben ignorar o podrían filtrar información sensible, así que ojo 👀.

Dentro de este archivo deberán definir las variables que cambian dependiendo de quien está utilizando el programa, por lo que deberían crear variables de entorno para todas las variables anteriormente mencionadas a excepción de dialect, que siempre será la misma (todos deben trabajar con Postgres).

Su `.env` debería quedar de esta forma (obviamente con su información):
```
DB_USERNAME=postgres
DB_PASSWORD=hola
DB_DATABASE=proyecto
DB_HOST='localhost'
```
Es importante que esto deben agregarlo en su README para que su ayudante sepa que variables de entorno debe crear.

Una vez tienen esto listo, solo basta con que hagan uso del comando `yarn sequelize-cli db:create` para poder crear la base de datos en su computador (comando que deben correr todos los integrantes para que la base de datos se les cree).

----

### Recomendación

Si quieren que todos los integrantes del grupo tengan los mismos datos en la base de datos al momento de crearla, pueden hacer uso de seeds. Les dejo el link a la [documentación](https://sequelize.org/docs/v6/other-topics/migrations/#creating-the-first-seed) por si lo quieren revisar.

Saludos y cualquier duda pudiese haber quedado no dudes en hacerla 😄.

**Comment by teresaorellana** [comment]
Entonces se deben crear todos los modelos con sus atributos, de nuevo en la nueva base de datos?

**Comment by Mamunoz42** [comment]
> Entonces se deben crear todos los modelos con sus atributos, de nuevo en la nueva base de datos?

Hola @teresaorellana 😄

Estos se crearán automáticamente cuando ustedes hagan `yarn sequelize-cli db:migrate`.

Es importante recordar que las migraciones son una serie de "instrucciones" que sigue sequelize para poder interactuar con la base de datos y crear modelos, eliminar modelos, agregar atributos en modelos, etc.

Lo importante es que los pasos a seguir para tener la base de datos funcionando en su computador (una vez alguno del grupo ya hizo la configuración inicial) son:
- `yarn sequelize-cli db:create`
- `yarn sequelize-cli db:migrate`

En caso de que tengan seed deberían correrlas después de la migración.
