### ISSUE TITLE
[T1] Documentación del proceso

### ISSUE THREAD

**Issue by antoniamerino** [IIC2513/Syllabus-S1-2024-1#4]
La documentacion del proceso va en el readme despues de la explicacion del codigo?

**Comment by Mamunoz42** [comment]
Hola 😄!

La documentación del proceso hace referencia efectivamente poder dejar claro todo lo que se hizo en el código, y el proceso que siguieron para obtener la información solicitada, por lo que, la explicación del código también es parte de lo que se evaluará como documentación.

Saludos ✌🏽
