### ISSUE TITLE
[E2] Error(`${this.name}.belongsToMany called with something that's not a subclass of Sequelize.Model`);

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#40]
Hola! Instanciado associates entre dos modelos con entidad - relación N a M entre estos 2, me empezó a arrojar el error presente en el titulo de la issue. Originalmente tenía hacia ambos lados un HasMany entre ambos pero al buscar en la [documentación de sequelize](https://sequelize.org/docs/v6/advanced-association-concepts/advanced-many-to-many/) encontré que era con belongsToMany, pero me sigue tirando el mismo error. Como se dijo en la cápsula, tuve cuidado con crear los modelos de manera que las migraciones puedan hacerse correctamente (crear modelos dependientes para el final), por lo que no se me ocurre por qué podría ser este error. Las migraciones corrieron sin problema para la base de datos y ahora que estoy intentando conectar algunas cosas del backend con frontend me encontré con este error al correr el nodemon en el backend.

**Comment by nanglada** [comment]
Hola! ⭐️
Este problema es típico cuando ocurre uno de dos: 
1. Los modelos no están creados correctamente.
2. Los modelos no se importan de manera correcta en el archivo en donde esta haciendo la relación.
Entiendo que tu dices que si están bien creados, pero recomiendo igual revisarlos una vez más por si acaso (a veces se nos pasan detalles que no alcanzamos a ver a primera vista) y que veas lo del punto 2. Cuéntame cómo te va con eso.
Igual, recomiendo fuertemente googlear el error porque es probable que no seas el primero en tenerlo, sino que la mayoría de estos temas ya han sido resueltos en Internet antes. 
Mucha suerte! Avísanos cualquier cosa

**Comment by rodrigoogalde** [comment]
Hola!
Podrías subir el modelo E/R a tu repositorio para revisarlo?
Me puedes hablar por telegram (@rjogalde) o responder esta issue

**Comment by rodrigoogalde** [comment]
Hola!
Respondo esta issue para dejar constancia de como solucionar este error.

Este error suele pasar cuando se intenta modelar un problema en donde 2 entidades tienen varias relaciones entre si. Para entender esto mejor, se toma el siguiente caso:

Queremos modelar varios usuarios que se registran a varios cursos de la universidad, uno pensaría que la relación puede ser N:N, ya que varios alumnos tienen varios cursos, sin embargo en términos de modelos relacionales no es posible, por lo que ocurre el error mencionado en el título de esta issue.

El modelo que se viene a la cabeza es parecido a esta imagen (que no es posible de modelar de esa manera):
![image](https://github.com/IIC2513/Syllabus-S1/assets/85193399/86556bd0-ebe6-4c04-9295-b2cc130752ce)

Para solucionar este problema de relación, es necesario crear una tabla intermedia, que relacione a ambos modelos de manera indirecta, con lo que se evitaría tener una incongruencia en las relaciones. Para esto, la tabla `enrollment` puede ser utilidad. Esta debe tener los siguientes atributos:

- `user_id`
- `course_id`

Por lo que quedaría la tabla algo así:

| user_id | course_id |
|---------|-----------|
| 1          | 5             |
| 2          | 4             |
| 1          | 3             |
| 1          | 4             |

y nuestro modelo de la siguiente manera:
![image](https://github.com/IIC2513/Syllabus-S1/assets/85193399/eb481333-11cb-4ad4-83f3-8f21623a68ea)

Finalmente, decimos que:
- `User` has many `Enrollment` (con la foreign Key `id`)
- `Enrollment` Belongs To `User` (con la foreign Key `user_id`)
- `Course` has many `Enrollment` (con la foreign Key `id`) 
- `Enrollment` Belongs To `Course` (con la foreign Key `course_id`)

Con esto solucionamos nuestro problemas de relaciones (se puede aplicar para cualquier problema con las mismas características)

Espero que sea de ayuda!
