### ISSUE TITLE
[E2] Uso de ES6 en vez de cjs

### ISSUE THREAD

**Issue by ComPups** [IIC2513/Syllabus-S1-2024-1#41]
Hola! Después de la confusión entre usar CJS y ES modules. Terminamos optando por usar ES6 lo cual para funcionar necesita que cambiemos las extensiones de los archivos que importan/exportan a .mjs. Hay algún problema con eso? o si se puede?
Pregunto para asegurarnos y seguir trabajando bajo esas reglas.

**Comment by nanglada** [comment]
Hola! No hay problema con eso,  no se preocupen. 
Mucho éxito
