### ISSUE TITLE
[E2] EADDRINUSE: address already in use.

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#42]
Hola! No logro salir de este error sobre que el puerto 3000 ya está en uso, he probado mediante varios métodos para ver las direcciones en uso y 3000 no está siendo usada, hasta use kill-port de yarn para matar cualquier instancia pero me dice que no hay nada en el puerto 3000 pero me sigue saliendo el error. Hay chance de que sea porque esté usando mal koa o algo?
![Screenshot 2023-10-26 at 13 38 56](https://github.com/IIC2513/Syllabus-S1/assets/101355363/6ef7bd8f-6d7c-4a25-a5a7-b51e5f9b675a)

**Comment by rodrigoogalde** [comment]
Hola!
Para poder cerrar un puerto que esté escuchando debes usar el siguiente comando:

`sudo lsof -i :3000` para ver puertos en uso (En este caso el puerto `3000`)
`sudo kill -9 PIB` para eliminar el puerto (Debes remplazar el PIB por el numero de la lista que te salga en esa columna)

**Comment by TTrincado** [comment]
Es que ya hice esas cosas, al buscar que se está usando en el puerto 3000 me dice que está libre, y lo mismo al intentar matarlo me dice que no se puede debido a que está libre y no hay procesos en el puerto. Es posible que un mal manejo de koa o alguna de las librerías provoque este error?

**Comment by rodrigoogalde** [comment]
Puedes correr el primer comando y subir un pantallazo de lo que te aparece en consola?

**Comment by TTrincado** [comment]
Claro! Al utilizar el primer comando después de pedirme la contraseña no pasa nada:
![Captura de pantalla 2023-10-27 a la(s) 00 17 21](https://github.com/IIC2513/Syllabus-S1/assets/101355363/25478365-b341-4d59-9c36-027c2151fe9f)
Buscando en google encontré que con kill-port de yarn puedo apagar cualquier instancia en el puerto, pero sale esto:
![Captura de pantalla 2023-10-27 a la(s) 00 18 18](https://github.com/IIC2513/Syllabus-S1/assets/101355363/ebb970ea-17ff-4ed7-bfc3-b50534e86026)

**Comment by nanglada** [comment]
Hola! El problema no debería ser Koa. Sin embargo, para comprobarlo podrías intentar cambiar el puerto que estás usando y así revisas si el problema es el puerto 3000 o si es tu aplicación.

**Comment by TTrincado** [comment]
Efectivamente, fue un mal uso de Koa u.u, tenía un app.listen en el puerto 3000 en el archivo app.js y en el index.js, por lo que ocurría eso. Muchas gracias de todas formas! :))
