### ISSUE TITLE
[T3] Duda sobre modificación y creación de archivos

### ISSUE THREAD

**Issue by gabo1243** [IIC2513/Syllabus-S1-2024-1#43]
Hola, estaba viendo el código de la tarea 3 y vi que todas las clases y ejecución está en ```jwt_auth.py```.  Entonces, ¿Puedo dividir las clases, funciones y ejecución en distintos archivos? (para que quede más ordenado para mí).

Gracias de antemano.

**Comment by nanglada** [comment]
Hola! Sii, no hay problema. Ten cuidado eso sí con explicar en tu README como está distribuido tu nuevo código y explícitamente cómo correrlo. 
Mucha suerte
