### ISSUE TITLE
[E2] Error al leer config.js cuando quiero hacer migraciones

### ISSUE THREAD

**Issue by ComPups** [IIC2513/Syllabus-S1-2024-1#44]
Hola! Resulta que el servidor inicia al hacer run dev, pero al momento de querer realizar migraciones, ahora que estamos usando ES6, sequelize-cli arroja un error no identificable al leer la configuración, en el peor de los casos tendremos que volver a 'cjs', pero quería saber si hay alguna otra cosa que pueda estar afectando. Lo único que encontré al respecto fue un hilo que no tuvo respuesta. Estoy empezando a pensar que sequelize no es compatible con el sistema de Import y export.

**Comment by nanglada** [comment]
Hola! Es posible que estén usando requiere en alguno de sus archivos y que ese sea el problema. En específico, están seguros que tienen la configuración de Sequelize escrita correctamente? Sequelize debería funcionar con import y export así que por ahí no debería estar el tema. Si quieres cuéntame específicamente cuál es tu error para ver si te puedo ayudar mejor. 
Quedo atenta!

**Comment by ComPups** [comment]
Gracias por la pronta respuesta! El al colocar import y export en el .sequelizerc, me arroja el siguiente error : /home/andres/Web/web-ada_backend/grupo_Web-Ada_backend/.sequelizerc:1
import path from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module

**Comment by nanglada** [comment]
Su package.json tiene cambiado el "type: module"? Investigando, estoy viendo que en general ese error ocurre por eso.

**Comment by ComPups** [comment]
Si!

**Comment by ComPups** [comment]
Por ej, si corro el código con run dev. Funciona sin problemas, es solo al usar sequelize-cli

**Comment by nanglada** [comment]
Entiendo! Estuve buscando y este [issue de StackOverflow ](https://stackoverflow.com/questions/36632748/es6-and-sequelize-cli) parece ser similar a lo que me dices. Aquí dan varias soluciones que podrían probar. Y sino, siempre está la opción de volver a usar CommonJS (a menos de que lo hayan cambiado por una razón muy particular).
