### ISSUE TITLE
[T3] Inputs

### ISSUE THREAD

**Issue by Fernanda1232123** [IIC2513/Syllabus-S1-2024-1#45]
Hola!

¿Para la tarea se espera que el programa pida al usuario el mail, rol y contraseña para registarse? ¿O se hace hardcodeado como está en la tarea?

Independiente de la respuestas a estas preguntas, ¿con que me den mensajes de éxito en todas las funciones y se escriban los datos del usaurio en USERS_DB en variables.py es todo lo que pide la tarea?

**Comment by nanglada** [comment]
Hola! Los inputs tienen que estar hardcodeados nomás, tal como está en el template que les dimos. 
Sobre la segunda pregunta, con eso está perfecto. Asegúrate de retornar exactamente lo que se pide por enunciado en cada función eso sí!
