### ISSUE TITLE
[T3] Problema para importar bcrypt

### ISSUE THREAD

**Issue by SebastianRosselot** [IIC2513/Syllabus-S1-2024-1#49]
Hola! Instalé bcrypt ejecutando "pip install bcrypt", y aún así me aparece el error "Import "bcrypt" could not be resolved Pylance(reportMissingImports)". Cómo puedo hacer para resolverlo? 

Saludos!

**Comment by nanglada** [comment]
Hola! Estuve investigando y parece que el problema es con el Python Path Interpreter en el que estás tratando de instalar bcrypt. Mira este [issue de StackOverflow ](https://stackoverflow.com/questions/68486207/import-could-not-be-resolved-could-not-be-resolved-from-source-pylance-in-vs-code)y ve si te sirve! Vi que habían hartas respuestas que podrían ser útiles en tu caso. Aquí el problema es con otra librería pero es la misma idea. 
Ojalá te sirva

**Comment by SebastianRosselot** [comment]
Había intentado buscar issues relacionadas en stackoverflow y no había encontrado, ahí me metí a la issue que mostraste y la segunda solución de hacer "Python: Clear Cache and Reload Window" me funcionó. 

Muchas gracias!!

**Comment by nanglada** [comment]
Buenísimo! Suerte
