### ISSUE TITLE
[T1] Formato entrega

### ISSUE THREAD

**Issue by vdelfierro** [IIC2513/Syllabus-S1-2024-1#5]
Es 100% necesario un .py y un .md? Digo porque un cuaderno .ipynb cumple con mostrar código y documentación simultáneamente, y podría ser mas intuitivo de leer/entender.

**Comment by Mamunoz42** [comment]
Hola! ✌🏽

Comprendo tú punto de vista, sin embargo, es importante que se respete el subir un archivo `.py` y uno `.md`. Esta petición se hace con la intención de que puedan explicar su código de forma clara sin tener el respaldo inmediato. Además, si gustan agregar código en la documentación para explicar algo mejor, son libres de hacerlo.

Saludos 😄
