### ISSUE TITLE
[T3] Definición de Token

### ISSUE THREAD

**Issue by clangoi** [IIC2513/Syllabus-S1-2024-1#50]
Hola, no entiendo qué es un token, y/o para qué se usa, he buscado ejemplos con bcrypt, pero, creo que no estoy entendiendo bien porque no veo que usen algo con "tokens" entonces no sé :(

**Comment by nanglada** [comment]
Hola! Un token es cuando se sustituyen elementos de datos sensibles (como lo son nombre, email, contraseña) por un equivalente no sensible que no tiene un significado de por sí. Estos se usan para la autorización y autenticación en páginas web. 

Recomiendo harto ver las diapositivas de clases, ahí se vió bien en detalle que es un Jason Web Token y cómo funciona. La documentación de JWT tambíen es bien útil y te puede servir. 

Ojalá te quede más claro ahora :)
Cualquier cosa me cuentas
