### ISSUE TITLE
[T3] Tiempo de expiración en JWT

### ISSUE THREAD

**Issue by nicoschwend** [IIC2513/Syllabus-S1-2024-1#51]
Se espera que agreguemos nosotros un tiempo de expiración al token supongo. Pero en que parte lo agregamos? podemos modificar el payload ohay que hacerlo de otra forma?

**Comment by nanglada** [comment]
Hola! Cómo estás? 

Sí, el tiempo de expiración del token debe ir en el payload. Tienen que agregarlo uds.
