### ISSUE TITLE
[T3] Formato de revisión

### ISSUE THREAD

**Issue by AndrewVenegas** [IIC2513/Syllabus-S1-2024-1#52]
Hola!

Quería preguntarles sobre cómo va a ser la revisión de la tarea. Esta se revisará solamente a nivel de output?? o analizarán función a función? 

 Y también me gustaría saber qué recomendaciones nos dan para verificar que nuestra tarea esté funcionando correctamente, a parte de que el output haya salido exitoso. 
 
 Saludos!

**Comment by nanglada** [comment]
Hola! Usaremos tests para revisar los outputs de las funciones. Sin embargo, si es que estos no pasan, se revisará a nivel de código las funciones para poder darles puntaje parcial. 

Sobre qué hacer para verificar que la tarea esté funcionando, pucha, si es que el output parece exitoso, entonces debería estar todo bien. Revisa bien que lo que esté retornando cada una de tus funciones con lo que se pide en el enunciado. Pero, en general, no hay mucho más que hacer.

**Comment by AndrewVenegas** [comment]
Super! Muchas gracias por la pronta respuesta. Saludos!
