### ISSUE TITLE
[T3] Última pregunta README

### ISSUE THREAD

**Issue by ignaciachacon** [IIC2513/Syllabus-S1-2024-1#53]
Hola! No entiendo bien a qué se refiere la última pregunta del README: "¿Por qué la firma creada en su código es válida?", se refiere a que tenemos que explicar cómo hicimos la firma y explicar por qué es correcta?

**Comment by nanglada** [comment]
Hola! Eso mismo es lo que tienen que responder, explicar cómo hicieron y cómo funciona su firma y explicar por qué es correcta. Suerte ⭐️

**Comment by ignaciachacon** [comment]
Gracias!
