### ISSUE TITLE
[T3] Que se entiende como payload y headers validos

### ISSUE THREAD

**Issue by IgnAMS** [IIC2513/Syllabus-S1-2024-1#54]
Hola! Quería preguntar que se entiende como header y payload válidos. 
Esto se refiere a que sean diccionarios?  Se refiere a que tengan algunas llaves? Se refiere a que algún valor de alguna llave sea consistente?
![imagen](https://github.com/IIC2513/Syllabus-S1/assets/42097387/d01c2af6-048b-49ca-8c75-1c7e50f64b9b)

Saludos!

**Comment by nanglada** [comment]
Hola! 🌼
Cuando hablamos de headers y payloads válidos, estamos diciendo que deben ser diccionarios que contienen la información mínima para poder crear un token. Esto incluye el algoritmo de encriptación, el tipo de token, etc. 
Ojalá te quede más claro ahora.
Cualquier cosa me avisas.

**Comment by IgnAMS** [comment]
Esta super! 
Muchas gracias :D

**Comment by IgnAMS** [comment]
Debemos manejar casos que se manden playloads o headers invalidos? o no los manejamos y asumimos que siempre mandaremos validos?

**Comment by nanglada** [comment]
Para el header, pueden utilizar el algoritmo dado en variables para arreglarlo en caso de que le falte información necesaria. En cualquier otro caso, basta con que lancen una excepción. No es necesario que los manejen

**Comment by IgnAMS** [comment]
Gracias!
