### ISSUE TITLE
[T3] Uso de hmac y hashlib

### ISSUE THREAD

**Issue by BastianCardenash** [IIC2513/Syllabus-S1-2024-1#55]
¿Está correcto el uso de estas librerías (hmac y haslib, que estan importadas en el codigo base) para poder crear el signature del token?

**Comment by rodrigoogalde** [comment]
Hola!
Sí, puedes usarlas sin ningún problema.
Las que no se pueden usar se encuentran detalladas en el enunciado 
Saludos!
