### ISSUE TITLE
[T3] Problema con hmac.digest

### ISSUE THREAD

**Issue by ebenstom** [IIC2513/Syllabus-S1-2024-1#56]
Hola, me funciona en general el código pero tengo un problema con la función digest de hmac, me sale:

msg = hmac.digest(
File "/usr/lib/python3.8/hmac.py", line 184, in digest
    inner.update(msg)
TypeError: object supporting the buffer API required

es muy extraño pq me metí a la documentación de python de hmac y sale que se usa así como lo tengo:
hmac.digest(key=secret, msg=token, digest=hashlib.sha256)

Además como el error es "TypeError: object supporting the buffer API required" no se como arreglarlo y en internet tampoco he encontrado algo que me ayude. Lo único que creo según lo que me he dado cuenta es que probablemente venga de como estoy usando el secret, ya que lo codifico con encode(utf-8) y luego le hago encode a base64 (pero sin esto no me funcionaba pq la función pedía que el secret esté en bytes y no str)

**Comment by rodrigoogalde** [comment]
Hola!
Para usar el método `digest` de hmac, puedes intentar usarlo de la siguiente forma:

```
hmac(key, msg=None, digestmod='').digest()
```

Si revistas a detalle la documentación, en el método `new`, este te retorna un objeto `hmac`, en donde en el método digest, te dice que sobre este objeto puedes aplicarle el método digest, que es lo equivalente a hacer lo que estás haciendo.
Con respecto al resto, según como estás codificando y haciendo el encode estas bien.

Si no te funciona puedes responde por aca

Saludos!

**Comment by ebenstom** [comment]
Ya, estoy cachando que no funciona porque la función hmac.new(...) retorna un objeto HMAC, entonces luego se le puede aplicar por ejemplo objeto = hmac.new(...).digest(), y ahí objeto será un string, sin embargo parece un string loco (como que está más encriptado parece), entonces no estoy cachando como recuperar el mensaje del objeto, lo otro que me deja hacer en una misma función el hmac.new y depués el .digest(), pero cuando retorno el token como objeto HMAC no me deja aplicarle digest() en la función de decode.
