### ISSUE TITLE
[T3] Método encode

### ISSUE THREAD

**Issue by isidoraabumohors** [IIC2513/Syllabus-S1-2024-1#58]
Hola,

Tengo una duda respecto al método. En el enunciado sale que hay que mandar un header y un payload válido. Podemos asumir que el header y el payload que recibe la función contienen toda la información necesaria, como el algoritmo de codificación, o tenemos que agregarle cosas al header y al payload?

Gracias!

**Comment by isidoraabumohors** [comment]
Mi pregunta va más que nada ya que en la tarea se define la variable ALGORITHM, pero según entiendo esto va en el header y no es necesario utilizarlo en el resto del código. Por eso, si el header ya viene listo, no entiendo dónde debemos ocupar esa variable, o si debemos modificar el header que recibe la función para agregarle la información del algoritmo?

**Comment by nanglada** [comment]
Hola! La idea es que revisen si es que en el header está toda la información necesaria para generar el token (entre ellos, el algoritmo). Para eso usas la variable ALGORITHM. 
Ojalá quede más claro ahora :)
Éxito!

**Comment by isidoraabumohors** [comment]
Ya perfecto! Entonces bastaría con revisar que el header que construimos nosotros en la función login contenga toda la información? Y en caso de que no contenga dicha información, es preferible que la agreguemos en ese método, o que simplemente se retorne un mensaje de error indicando que el header es inválido al no contener la información?

**Comment by nanglada** [comment]
Eso mismo! Pueden hacer lo que les salga más fácil, mandar un error o agregarle lo que le falta al header.

**Comment by isidoraabumohors** [comment]
Gracias!!
