### ISSUE TITLE
[T3] Pregunta algorithm

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#59]
Hola! Por alguna razón usar el algoritmo HS256 no me funciona para realizar mis encodings y signatures con el token. Puedo cambiar el algoritmo a por ejemplo, sha256, ya que este si me lo toma como un algoritmo válido en hmac?

**Comment by rodrigoogalde** [comment]
Hola!
No hay problema si quieres usar el sha256
Saludos!
