### ISSUE TITLE
[T1] Problema con ChromeDriver

### ISSUE THREAD

**Issue by RorroPoblete** [IIC2513/Syllabus-S1-2024-1#6]
Hola, al intentar instalar ChromeDriver, la versión más reciente que está disponible es la 116.0.5845.96 y yo tengo chrome  116.0.5845.110. Al intentar usarlo igual, chrome no se abre.
Muchas gracias

**Comment by Mamunoz42** [comment]
Hola @RorroPoblete ✌🏽

Te sale algún tipo de error cuando corres tú código?

Si creas un programa `.py`como el siguiente que te sale?
```python
from selenium import webdriver


driver = webdriver.Chrome()

driver.get("http://selenium.dev")

driver.quit()
```

Lo otro a tener en consideración es que la primera ejecución siempre es muy lenta, por lo que es normal que tarde en abrirse.

En caso de que sigas teniendo problemas por favor seguir contestando en esta misma issue.

Saludos 😄

**Comment by pascualferrer** [comment]
Hola. Estoy teniendo un problema similar. En chrome tengo la versión 116.0.5845.141. Al ejecutar el código que pusiste arriba se abre el navegador y se cierra. Si elimino la línea driver.quit() también. Se abre y muy rápidamente se cierra. Intenté empezar a trabajar a través de Edge, para el cuál sí tengo un EdgeDriver compatible para la versión de mi Edge (116.0.5845.141) y aún así al definir el driver y hacer el get, se abre la página y se cierra muy rapidamente. Es normal que se cierre? No debería mantenerse abierto para así poder empezar a ocupar el devtools?

**Comment by Mamunoz42** [comment]
Hola @pascualferrer

Ese comportamiento que tiene selenium es el normal, ustedes deben usar las devtools en su navegador como se hizo en la ayudantía 1 (viernes pasado), ya que selenium solo ejecutará las acciones que ustedes le indiquen.

También es importante notar que el driver que utilice selenium no tiene relación con el navegador que ustedes utilicen, ya que no es lo mismo.

Si quedan dudas no dudes en hacerlas 😄 

Saludos ✌🏽
