### ISSUE TITLE
[E3] Plazo Entrega N°3

### ISSUE THREAD

**Issue by AndrewVenegas** [IIC2513/Syllabus-S1-2024-1#60]
Hola!

Quería preguntar por el plazo de la entrega de la Entrega 3. Como desde hace unas tareas pasadas venimos con un feriado que hizo que se corrieran ciertas entregas y tareas, sumado a que la Tarea N°3 se entregó el viernes 3, había asumido que la Entrega N°3 se iba a liberar el día sábado 4 de noviembre, por lo cual tendríamos plazo hasta el sábado 18 (2 semanas). 

Por lo mismo, quería saber si esto es así, o se sigue la planificación original del semestre, quedando esta entrega para el viernes 17.

Saludos!

Andrés Venegas

**Comment by nanglada** [comment]
Hola! Pucha, si la entrega se mantiene para el viernes 17. Tuvimos que cambiar un par de fechas por feriados que no teníamos considerados, pero esta entrega siempre se dijo que se iba a mantener para el viernes (tanto en el enunciado, como en el anuncio que les mandé cuando la subí el viernes 3).
