### ISSUE TITLE
[E3] Consulta error Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by TTrincado** [IIC2513/Syllabus-S1-2024-1#61]
Hola! Al instanciar el login del usuario con token me tira el error mostrado en la imagen, este error solo sucede cuando intento implementar el token, al sacar ese contexto y simplemente dar un status 201 no me tira problema, por lo que no sé como debuguear muy bien esto (revisé las cápsulas y tampoco veo algo muy diferente a mi código como para entender el problema). Esto también me pasaba antes pero lo logré solucionar con koa cors2 al intentar comunicar frontend con backend, pero ahora el problema volvió con esto. Alguna idea de como abordarlo?

PD: Al probar en postman el login si funciona, es solo cuando lo intento probar conectando al frontend! 

<img width="497" alt="Screenshot 2023-11-14 at 13 27 00" src="https://github.com/IIC2513/Syllabus-S1/assets/101355363/78f940f7-39d2-4039-bca3-ec7de1dd6be6">

**Comment by nanglada** [comment]
Hola!
Primero que nada, es súper normal que este problema esté pasando en el browser pero no en Postman porque, en general, los problemas de CORS ocurren debido a las restricciones de seguridad que los navegadores revisan pero que Postman no tiene en cuenta. En específico, esto tiene que estar pasando porque CORS suele tener problemas "procesando" (por decirlo de alguna manera) headers menos usuales (como lo es en este caso con el uso de tokens). 

Encontré esta [issue de StackOverflow](https://stackoverflow.com/questions/10636611/how-does-the-access-control-allow-origin-header-work) que explica mejor que yo porqué les está pasando esto y que tiene varias soluciones. No todas aplican (muchas hablan de lenguajes que nada que ver con nosotros, pero hay un par con node que les pueden servir). Probablemente van a tener que hacer algo setear en su backend que se agreguen los headers necesarios para que CORS funcione. Algo así debería ser (no les quiero asegurar que va a ser exactamente eso, pero me tinca que por ahí va).

<img width="551" alt="image" src="https://github.com/IIC2513/Syllabus-S1/assets/62104901/ef6fcae1-8c56-4b6b-b911-326f3786f105">

Ojalá les sirva!
Mucha suerte 🍀
