### ISSUE TITLE
[E4] Deploy Frontend

### ISSUE THREAD

**Issue by AndrewVenegas** [IIC2513/Syllabus-S1-2024-1#62]
Hola! Estaba tratando de hacer el deploy del frontend en Netlify a través de mi cuenta de github pero sale que no tengo los permisos para que netlify pueda acceder al repositorio. ¿Será posible que puedan autorizar esto para todos? Esto es lo que me aparece:

![image](https://github.com/IIC2513/Syllabus-S1/assets/105684850/eb1bf2e6-042a-4654-8774-6f691df605df)

También estuve tratando de hacer otras cosas, quise hacer un fork del repo para poder subirlo desde un repositorio público, pero la opción de hacer fork en el frontend está deshabilitada. Y también quise hacer una carpeta .zip de los archivos que tenía localmente en mi computador, pero salen errores de que hay archivos que no se pueden leer.

Saludos!

**Comment by Lexiesm** [comment]
Hola Andrew! :) 
lo que te recomiendo es copiar/resubir tu carpeta raíz del repo de frontend a un repositorio personal, con eso no debiese haber problemas para hacer el deploy en Netlify.
Me avisas por aquí si te funciona!

Saludos!

**Comment by AndrewVenegas** [comment]
Holaa, gracias por la idea! Estuve tratando de hacerlo, pero la verdad es que no creo que sea una opción muy optima. Pasa que la aplicacion con todos sus archivos pesa mucho, y muchos archivos tampoco los detecta al hacer el traspaso de la información. Lo hice de momento para probarlo, pero no veo factible hacer la entrega de la pagina web haciendo el deploy de esta manera :c

**Comment by nanglada** [comment]
Hola! Puedes descargar como zip directamente tu carpeta desde github y con eso crear tu repositorio personal. Ahí no deberían perderse archivos ni tener problema porque son muy pesados. Esa es la forma en la que se realizan la mayoría de los deploys en este curso :)

**Comment by AndrewVenegas** [comment]
Holaa! Supeer ahi si pude hacerlo bien y no fue muy complicado. Muchas gracias a las dos🙌
