### ISSUE TITLE
[E4] Git: Problema pegado en "Checking for ability to merge automatically…"

### ISSUE THREAD

**Issue by SebastianRosselot** [IIC2513/Syllabus-S1-2024-1#64]
Hola! Creé una pull request desde mi rama personal, y cuando la clickeo para resolver conflictos existentes se queda pegado infinitamente en "Checking for ability to merge automatically… Hang in there while we check the branch’s status.". Por lo anterior, no puedo hacer el merge de mi rama a main ya que ninguno de los botones aparece. Además, en consola no aparecen errores.

Intenté hacer sign out y luego sing in, ingresar desde otro computador, y también cerrar la pull request y crear una nueva, y nada me funcionó.

**Comment by nanglada** [comment]
Hola! Me acabo de meter a tu repo y el botón de "Resolve conflicts" en la página donde está la pull request parece funcionar bien. Alcanzas a entrar a ese botón o se te queda pegado antes de eso? 

Quizás podrías intentar cambiar de navegador o ver si alguno de tus compañeros de grupo pueden ayudarte a resolver los conflictos? No tendría por qué no funcionarte la verdad. 

Cuéntame por acá si es que eso te funciona para buscar otra solución sino. 
Suerte!

**Comment by SebastianRosselot** [comment]
Hola! Finalmente lo dejé harto rato cargando y me dejó apretarlo. Hablé con mi ayudante, y me dijo que a él le había pasado lo mismo en un repo personal alrededor de la misma hora, por lo que parece que era un problema de GitHub. Muchas gracias!
