### ISSUE TITLE
[E4] Deploy backend - dotenv error

### ISSUE THREAD

**Issue by naderhadweh** [IIC2513/Syllabus-S1-2024-1#65]
![Captura de Pantalla 2023-11-27 a la(s) 20 50 06](https://github.com/IIC2513/Syllabus-S1/assets/89283382/441f836f-bb71-4901-961a-8cef8fad9f62)

Hola, cuando intentamos hacer el deploy del backend con render nos sale ese error. No logramos encontrar por qué ocurre

**Comment by nanglada** [comment]
Hola! Está muy raro el caso la verdad. Buscamos harto con el equipo docente y revisamos tu código y no encontramos el error. Tu script start.js parece estar correcto. Sabes si el problema es solo con dotenv o también con el resto de las librerías que están usando? Podrían intentar eliminar esta librería para probar si el problema es con esta o con todo el resto. Cuéntame que concluyen y si es que logran entender que está pasando. 
Quedo atenta.

**Comment by naderhadweh** [comment]
Hola, parece que el problema era por unas dependencias de eslint-typescript. Ahora las borramos y nos sale otro error. No entendemos que es, ya que cuando hacemos yarn deploy desde VSCode no no tira problema. Hemos revisado las environment variables y están bien. Qué podrá ser?
![Captura de Pantalla 2023-11-28 a la(s) 16 58 35](https://github.com/IIC2513/Syllabus-S1/assets/89283382/22af3ccd-1b9f-45c7-8778-13b6e0b51397)

**Comment by TTrincado** [comment]
Hola! Nos pasa lo mismo que al compañero :(. Saben de alguna solución?

**Comment by naderhadweh** [comment]
Creo que lo arreglé borrando el _development y _production de las variables que están en el config.js, pero no se si la idea era arreglarlo asi

**Comment by rodrigoogalde** [comment]
Hola!
Estuve revisando el error y una de las posibles causas puede ser que hayas definido tu BDD en postgres de la siguiente forma:
`basededatos_development`
En este caso el `_development`  esta "hardcodeado", ya que cuando se utiliza una BDD, se agrega automáticamente el `_development`.

Para solucionar esto debes modificar el archivo config.js.

Para poder usarlo de forma local:
```
  development: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: `${process.env.DB_NAME}_development`,
    host: process.env.DB_HOST,
    dialect: 'postgres',
    seederStorage: 'sequelize',
  },
  test: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: `${process.env.DB_NAME}_test`,
    host: process.env.DB_HOST,
    dialect: 'postgres',
    seederStorage: 'sequelize',
  },
  production: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: `${process.env.DB_NAME}_production`,
    host: process.env.DB_HOST,
    dialect: 'postgres',
    seederStorage: 'sequelize',
```

Para poder usarlo en el deploy:
```
const dotenv = require('dotenv');

dotenv.config();

module.exports = {
  development: {
    username: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
    host: process.env.DATABASE_HOST,
    dialect: 'postgres',
  },
  test: {
    username: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
    host: process.env.DATABASE_HOST,
    dialect: 'postgres',
  },
  production: {
    username: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_NAME,
    host: process.env.DATABASE_HOST,
    dialect: 'postgres',
  },
};

```

Recuerda también modificar el nombre de tu BDD local
