### ISSUE TITLE
[E4] Problema con deploy del backend

### ISSUE THREAD

**Issue by FlorenciaOnetto** [IIC2513/Syllabus-S1-2024-1#66]
<img width="856" alt="Captura de pantalla 2023-11-30 a la(s) 17 40 53" src="https://github.com/IIC2513/Syllabus-S1/assets/101374971/73c543a8-75f3-4518-9e4e-43cbd369851d">
Hola! Tenemos este problema al intentar hacer deploy, y no sabemos que puede ser :/
Pusimos bien las variables de entorno, así que no debería haber problema con eso.

**Comment by rodrigoogalde** [comment]
Hola!
Recuerda que para poder hacer el deploy correctamente, debes crear un archivo .env y colocarlo en la plataforma. En este caso el error que muestra es que no has entregado el nombre del usuario de postgres para poder acceder a la DB.

**Comment by FlorenciaOnetto** [comment]
Subí el archivo .env al repositorio de GitHub. Hay que subirlo a Render también?

**Comment by nanglada** [comment]
Hola! Tienes que especificar las variables de entorno al subir tu repo a Render. Te recomiendo revisar la cápsula de deploy, aprox en el minuto 19 (ahí hacen esa parte): https://www.youtube.com/watch?v=S9krVSTIlSo&t=499s
Ojalá te sirva!
