### ISSUE TITLE
[E4] Error deploy fronted

### ISSUE THREAD

**Issue by aedwardsg** [IIC2513/Syllabus-S1-2024-1#67]
Hola! Si nos corre el deploy, pero cuando abrimos la página a la que nos lleva después aparece en blanco. Al inspeccionarla, podemos ver lo que se adjunta en la foto. Esto es lo mismo que vemos cuando abrimos el localhost, pero el div con id=root se encuentra vacío a diferencia de cuando lo corremos en el localhost que si vemos toda la página.

![WhatsApp Image 2023-11-30 at 18 58 02](https://github.com/IIC2513/Syllabus-S1/assets/101359989/3946c697-d6d6-47ff-bb58-a691c90ed46d)

![WhatsApp Image 2023-11-30 at 19 00 08](https://github.com/IIC2513/Syllabus-S1/assets/101359989/68308e9f-aac5-4855-8a8a-9c5e6f5a55c5)

**Comment by rodrigoogalde** [comment]
Podrían enviar una foto de los que le aparece en la consola cuando hacen deploy?
