### ISSUE TITLE
[T4] Duda URL webhook

### ISSUE THREAD

**Issue by danilarco** [IIC2513/Syllabus-S1-2024-1#68]
Hola! Tengo una duda con la url proporcionada en la consola de ngrok. Cuando ejecuto el comando ngrok http [puerto], se me abre la consola de ngrok pero cada vez con un link distinto. En el enunciado dice que hay que definir la URL del webhook como una variable de entorno. Si el link de ngrok es dinámico y cambia cada vez que se ejecuta el servidor, como se puede definir como una variable de entorno? O debo poner en el README las instrucciones para asociar al bot con esta URL que va cambiando? Gracias de antemano!

**Comment by nanglada** [comment]
Hola! Pon en el README uno de los links que te haya dado (da lo mismo que este ya no sea válido), solo para que nosotros podamos ver que entiendes bien cuál tiene que ser el url del webhook. Se entiende? Cualquier duda pregunta nomás.
Suerte!
