### ISSUE TITLE
[T4] Librerías para consultas

### ISSUE THREAD

**Issue by pabloaylwin** [IIC2513/Syllabus-S1-2024-1#69]
Hola, en el enunciado dice que sólo se pueden usar las librerías de koa-parser y koa-router, pero se puede usar otra librería como axios al igual que durante todo el semestre para hacer las consultas a la API? O cómo se espera que se hagan las consultas si no es con axios u otro similar?
Gracias de antemano

**Comment by nanglada** [comment]
Hola! Originalmente, habíamos pensado que hicieran la consulta a la API con fetch (que no requiere librería externa), por eso no lo pusimos en el enunciado. Sin embargo, también pueden usar axios. No hay problema con eso. 
Mucha suerte!

**Comment by JoseTomasSoto** [comment]
Se puede usar express?

**Comment by nanglada** [comment]
Hay alguna razón en particular por la que quieres usar Express? En general, preferimos que usen Koa para que los ayudantes puedan corregir más fácilmente.

**Comment by JoseTomasSoto** [comment]
Simplemente me sale más fácil con express, creo entenderlo mejor. Es legal?

**Comment by nanglada** [comment]
No, no puedes. El problema es que no todos nuestros ayudantes se manejan con Express así que es preferible (por temas de corrección) que uses Koa para la tarea. Suerte!

**Comment by IgnAMS** [comment]
Hola! Y se puede usar la libreria dotenv para el .env y la libreria de ngrok para manejar ngrok? El de la librería ngrok lo pregunto porque en el readme hablan sobre la librería y en verdad estamos usando como el ejecutable jajaja.

Saludos!

**Comment by nanglada** [comment]
Hola! La de dotenv sí, no hay problema. Y sobre ngrok, tienes razón realmente no es una librería, así que no se considera dentro del tema de "librerías prohibidas". Fue un error por parte nuestra ponerlo así en el enunciado. Se puede usar obviamente jaja no te preocupes por eso.
