### ISSUE TITLE
[T1] Submit form Buscacursos

### ISSUE THREAD

**Issue by ebenstom** [IIC2513/Syllabus-S1-2024-1#7]
Hola, he logrado usar las casillas para buscar los cursos, pero no he logrado utilizar el boton de buscar cursos. Este mismo está grabado como un input dentro de un form y no tiene id ni name propio. En internet no me sala nada que me ayude con esto y ya no se me ocurren más ideas de como enviar este form, por favor ayuda.

**Comment by clangoi** [comment]
Yo todavía no verifico si funciona, pero estoy tratando con el XPath, a lo mejor así funciona.

**Comment by Mamunoz42** [comment]
Hola 😄!

Efectivamente no tiene id y tampoco name 😞. Sin embargo, recuerda que existe otra forma de identificar los elementos en nuestro DOM, y esa son las clases. Si te das cuenta, el botón si tiene definida una clase, por lo que con esta información podrías encontrar el botón que necesitas.

Espero les sirva esto para que sigan avanzando en su tarea. Cualquier duda, pueden seguir respondiendo esta issue.

Saludos ✌🏽
