### ISSUE TITLE
[T4] Correr código con yarn

### ISSUE THREAD

**Issue by IgnAMS** [IIC2513/Syllabus-S1-2024-1#70]
Hola! Estaba preguntándome si para correr el código debemos crear un proyecto yarn o algo por el estilo. Que en el enunciado se menciona de entregar el archivo .js pero no me había preguntado antes como correr un código de javascript antes jajaja.

Saludos!

**Comment by rodrigoogalde** [comment]
Hola!
Te recomendamos usar yarn, ya que es lo que se ha usado en el curso. Pero puedes usar otra como npm.
Si utilizas otra, debes documentar como correr tu código para facilitar la corrección de tu tarea

Que estes bien!

**Comment by IgnAMS** [comment]
Muchas gracias!

**Comment by Moisnt** [comment]
Respecto a ejecutar el código podemos usar nodemon entonces?.
Saludos.

**Comment by nanglada** [comment]
Si, no hay problema. Eso si, tengan en cuenta que tienen que explicar paso a paso cómo correr su código.
