### ISSUE TITLE
[T4] Librería prohibida y complejidad bot

### ISSUE THREAD

**Issue by gabo1243** [IIC2513/Syllabus-S1-2024-1#71]
Hola, me surgieron unas dudas con respecto a la tarea 4 y ando un poco perdido:
 
1.	En el enunciado dice que solo se puede ocupar koa router y koa parser como librerías, por lo que he estado investigando, y para acceder a un bot de Telegram uno debe usar una librería. Los casos que estaba viendo ocupaban "node-telegram-bot-api”, pero no sé si es la idea ocupar esta o recurrir a algo más básico. En esta librería uno importa el bot conectándolo con el token y lo único que se hace es crear los comandos o endpoints que se ingresaran en el chat. Si no se puede ocupar esta, no entiendo el cómo conectarme al bot, ya que necesito una librería para acceder al bot con el token.
2.	¿Qué tan complejo debe ser las requests que se le pidan al bot? En el sentido de solo enviar la información que obtengo de la API pública o hacer algo extra con esa información
 
Gracias de antemano

**Comment by nanglada** [comment]
Holi! Sobre tus dos preguntas:
1. La librería que mencionas hace más fácil todo el proceso de hacer el bot y por lo mismo está prohibida. Además del parser y del router, pueden usar axios y dotenv, pero más allá de eso nada más. La idea es que creen este bot de la misma forma que hicieron el servidor de Koa de su proyecto.
2. Tan complejas con tu quieras. Si quieres hacer muy bacán y complicado, feliz. Pero sino, con tal de que hagas un GET a una API pública, está bien. 
Cualquier otra duda avísame!

**Comment by ebenstom** [comment]
Hola, sobre no poder usar la librería de "node-telegram-bot-api”, entonces como creamos un bot de telegram, tipo que no se bien que tipo de programa es exactamente un bot de telegram ni como hacer que exponga una API que deje que se conecte a telegram, y todos los tutoriales que he encontrado por el momento usan esta librería y crean el bot con "new TelegramBot", entonces no estoy entendiendo bien que tenemos que hacer.

**Comment by nanglada** [comment]
La librería "node-telegram-bot-api” hace de forma más sencilla el tema del bot. La idea es que uds hagan todo el proceso de crear un servidor que se conecte a Telegram a través de webhooks "a mano", es decir, utilizando solo las herramientas permitidas.  No se si queda más claro ahora.

**Comment by Dchungw** [comment]
Y sobre las librerías koa-logger y koa-body?

**Comment by nanglada** [comment]
No debería ser necesario que las usen pero si quieren, pueden usarlas

**Comment by Moisnt** [comment]
Hola, podemos usar koa-bodyparser?? Pregunto porque en el enunciado solo se menciona koa-parser

**Comment by nanglada** [comment]
Hola! Si, no hay problema
