### ISSUE TITLE
[T4] Comando para iniciar conversación

### ISSUE THREAD

**Issue by gabo1243** [IIC2513/Syllabus-S1-2024-1#72]
Hola, en el enunciado dice que se debe implementar un comando /start (o parecido) para que se comience la conversación con el bot. ¿A esto se refieren a que el bot solo conteste después de que se escriba /start o que el bot responda con información (de una consulta GET a la API) cada vez que se ejecute el comando (/start u otro dependiendo de la consulta de información que se quiera)?

Gracias de antemano.

**Comment by nanglada** [comment]
Hola! Puede ser cualquiera de las dos. Sin embargo, yo te recomendaría que el /start haga el fetch a la API externa y lo mande de vuelta a Telegram.

**Comment by Moisnt** [comment]
Podemos agregar más comando aparte de /start que hagan distintas cosas como saludar e informar sobre los otros comandos??

**Comment by nanglada** [comment]
Si, no hay problema. Tienen que tener mínimo un comando (por ejemplo, start) pero si quieren agregar más, está súper.
