### ISSUE TITLE
[T4] Creación del Bot

### ISSUE THREAD

**Issue by Moisnt** [IIC2513/Syllabus-S1-2024-1#73]
Hola, he visto en el enunciado y en las issues que se hace harto enfasis en que tenemos que hacer el bot desde 0. Encontré un video que explica cómo hacerlo y muestran que debemos crearlo directamente desde telegram ejecutando un comando. ¿Esto es parte de la creacion desde 0 o no podemos hacerlo así?

**Comment by nanglada** [comment]
Hola! Sii, necesitan crearlo con Telegram para conseguir el token de su bot. El "desde cero" es más que nada para que no usen librerías de Koa que les faciliten el desarrollo. 
Suerte!

**Comment by Moisnt** [comment]
Gracias!
