### ISSUE TITLE
[T4] Creación de bot en Telegram

### ISSUE THREAD

**Issue by IgnacioLanderos** [IIC2513/Syllabus-S1-2024-1#74]
Hola, tengo una consulta. Lo esperado en la tarea es que creemos un bot en la misma plataforma de Telegram con @BotFather y accedamos a ella con el token proporcionado? O lo mencionado no está permitido?

Gracias de antemano n.n

**Comment by nanglada** [comment]
Hola! Tal cual, eso tienen que hacer.
