### ISSUE TITLE
[T4] Uso de librerías

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2513/Syllabus-S1-2024-1#75]
Procedo a consultar si las siguientes librerías están disponibles para esta tarea:

1. telegraf
2. https
3. dotenv
4. axios

Gracias de antemano por las aclaraciones.

**Comment by NicoJGutierrez** [comment]
Me gustaría agregar algunas otras librerías para ver si están disponibles:
5. express
6. bodyparser
7. hapy
8. fastify
9. npm en lugar de yarn como gestor de paquetes (no es librería pero como no se ha hecho en el curso creo que vale la pena preguntar si lo puedo hacer)

**Comment by nanglada** [comment]
Hola! Primero que todo, ojo con leer las otras issues, varias de estas librerías ya han sido preguntadas antes. 

Ahora, de todas las que me preguntas, las únicas que pueden usar son: dotenv, axios y bodyparser. El resto están prohibidas. 

Y sobre npm, si no hay problema, ese tema lo pueden manejar como quieran.

**Comment by tadonisb** [comment]
No se puede usar koa/cors tampoco, entonces?

**Comment by nanglada** [comment]
No deberían necesitarlo, pero pueden si quieren.
