### ISSUE TITLE
[T4] Entregables y modularización

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2513/Syllabus-S1-2024-1#76]
Partiendo algo tarde aquí 😅
Recién me "desocupé" ayer.

Espero todavía respondan preguntas...

---

El enunciado dice que los entregables han de ser un `index.js` y un `readme.md`. Sin embargo, tengo la tendencia a modularizar archivos. ¿Es posible entregar un proyecto un poco más complejo?

Tras haber comenzado tengo lo siguiente...
```
.
├── app.js
├── bin
│   └── www
├── package.json
├── public
│   ├── images
│   ├── javascripts
│   └── stylesheets
│       └── style.css
├── routes
│   ├── index.js
│   └── route1.js
└── views
    ├── error.jade
    ├── index.jade
    └── layout.jade
```

Estimo que será más ordenado y fácil de leer que el spaghetti gigante que quedará en un puro index.js.

Asímimo, siempre lo puedo condensar a un puro `index.min.js` con otras herramientas, pero tampoco creo que sea la idea.

---

tl;dr:
¿Se puede entregar una tarea con más que solo 2 archivos?

**Comment by rodrigoogalde** [comment]
Hola!
Te pedimos que te apegues a lo que se pide en el enunciado, ya que así facilita mucho más la corrección de la tarea.
Si quieres puedes implementar funciones que realicen las acciones por comando, así puedes tener un código más limpio y fácil de corregir.

**Comment by nanglada** [comment]
Hola! Aprovecho de complementar la respuesta de Rodrigo. La idea es que su tarea sea simple, tanto en temas de desarrollo para uds, como para la corrección de parte de los ayudantes. Intenta de no complicarte y hacer un solo archivo index.js normal.
