### ISSUE TITLE
[T4] Librerías prohibidas

### ISSUE THREAD

**Issue by ljgonzalez1** [IIC2513/Syllabus-S1-2024-1#77]
...en caso de que se sigan respondiendo preguntas...

---

Estoy algo perdido con el tema de las librerías perdidas mencionadas en otras issues.
¿Existe un lugar donde estén escritas? (...que, de existir, claramente no he visto)

¿O es a medida se pregunta?

---

Hasta ahora tengo dentro de las no permitidas:

- telegraf
- https
- express
- hapy
- fastify
- node-telegram-bot-api

Y dentro de las permitidas

- koa router
- koa
- koa parser
- koa-bodyparser
- npm
- yarn
- dotenv
- axios
- bodyparser
- koa/cors

¿Qué hay de otras que se usan para el proceso de desarrollo, debug y documentación?
Como las siguientes

- eslint
- eslint-config-airbnb-base
- eslint-config-koa
- eslint-config-standard
- eslint-plugin-import
- eslint-plugin-n
- eslint-plugin-node
- eslint-plugin-promise
- eslint-plugin-standard
- nodemon
- debug
- @ladjs/koa-views
- jade
- koa-json
- koa-logger
- koa2-swagger-ui
- openapi-types
- swagger-jsdoc

**Comment by nanglada** [comment]
Hola! Ninguna de las que mencionas está permitida. No debería ser necesario para el desarollo de su trabajo y la idea es que tampoco se compliquen agregando cosas innecesarias.
