### ISSUE TITLE
[T4] Funcionamiento del ngrok y token del bot

### ISSUE THREAD

**Issue by IgnacioLanderos** [IIC2513/Syllabus-S1-2024-1#78]
Holaaaa tengo una consulta con lo que se espera con ngrok en la tarea.

Actualmente para que funcione mi bot, primero se necesita setear manualmente la conexión entre el bot de telegram y mi servidor local de la siguiente manera:

curl -F "url=https://<NGROK_URL>/webhook" https://api.telegram.org/bot<TOKEN_DEL_BOT>/setWebhook

Si lo documento en el README.md es suficiente? o es necesario que se automatice el proceso de alguna manera?

Si el caso es el segundo cómo se haría?

Gracias de antemano!

**Comment by nanglada** [comment]
Hola! Tienes que documentarlo nomás. No te preocupes
