### ISSUE TITLE
[T4] Uso de koa, y archivo .env

### ISSUE THREAD

**Issue by mmerkade** [IIC2513/Syllabus-S1-2024-1#79]
Hola. Tengo un par de preguntas.

1. Ya que se tiene que usar `koa-router`, me imagino que también está permitido usar `koa`, verdad?
2. El archivo `.env` que tenemos que crear, es parte de los entregables?

**Comment by nanglada** [comment]
Hola!
1. Si, sale en el mismo enunciado que tienen que usar Koa para desarrollar su tarea. 
2. El archivo .env nunca debe enviarse. Deben escribir en su README (hay una sección en el template que le dimos para eso) lo que tiene que tener este.

**Comment by mmerkade** [comment]
Ok, gracias!
