### ISSUE TITLE
[T1] Libreria requests

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2513/Syllabus-S1-2024-1#8]
Se puede hacer uso de esta librería?
Aprovechando la pregunta, se pueden usar librerías fuera de Selenium y Bs4?

Gracias!

**Comment by Mamunoz42** [comment]
Hola 😄!

No se puede hacer uso de la librería requests, ya que con Selenium y Bs4 pueden hacer todo lo solicitado en la Tarea. Se puede hacer uso de librerías externas mientras **NO** se relacionen con el scrapping web.

Saludos ✌🏽
