### ISSUE TITLE
[T4] Servidor local aparece como "no disponible"

### ISSUE THREAD

**Issue by tadonisb** [IIC2513/Syllabus-S1-2024-1#80]
Hola! Una consulta. Llevo la semana entera tratando de solucionar problemas y ya creo que me siento un poco superado. Por más que intento, busco soluciones en internet e intento de nuevo, mi servidor de Koa actua como si no estuviera disponible. Establezco el webhook en la URL que indico (hasta lo compruebo y me arroja ok: true y veo la URL pedida), Ngrok crea el túnel a Telegram, todo; pero aunque tengo el servidor en local corriendo y conectado con Ngrok, en uno de los puertos soportados por la API de Telegram, me siguen lanzando errores de que el servidor no está disponible. Intento hacer fetch o get con axios a la API que quiero consumir y, nuevamente, el problema parece ser que mi servidor "no está disponible". No he podido comprobar nada de mi avance porque apenas trato de conectar con algo fuera de local, me aparecen errores 404 y 503.

Puede ser que haya algo mal en mi computador? Continúo adelante con el código un poco a ciegas y documento bien en el README? O quizás dentro de las cosas que estoy asegurandome que están bien dejé algo afuera y eso puede ser?

**Comment by nanglada** [comment]
Hola! Dado que queda poco tiempo, te recomiendo harto seguir trabajando (tanto en el código como en la documentación), tal que, aunque no funcione el bot, igual logres obtener puntos por avance. No es lo ideal, claramente, pero es mejor eso a que no entregues.

Ahora, podrías subir lo que llevas de código a tu repositorio? Apenas tenga un ratito, lo reviso para ver si es que el problema es tu computador (que no debería ser) o qué puede estar pasando. Avísame cuando lo hayas subido!

**Comment by tadonisb** [comment]
Hola! Ya, muchas gracias, ahora mismo voy a mergear lo que tengo a main.

**Comment by tadonisb** [comment]
Hola! Ahora Ngrok tampoco me funciona:( vuelvo al estado de mi código en que estaba funcionando y me sigue arrojando el mismo error al intentar abrir la página por medio de la URL de Ngrok 

ERR_NGROK_3004
ngrok gateway error

The server returned an invalid or incomplete HTTP response.

Mi servidor está corriendo, con webhook establecido y verifiqué estar intentando acceder a la URL actualizada que la nueva sesión de Ngrok me dio:(

**Comment by juanfdezg** [comment]
Hola! Acabo de probar correr tu código en mi computador y si funcionó. Logré configurar bien el webhook y no me tira ningún problema con Ngrok. Eso sí, tuve que cambiar el puerto que estabas usando, ya que estabas usando el puerto 443 y los puertos inferiores a 1024 normalmente requieren privilegios de administrador en la mayoría de los sistemas operativos.  Prueba cambiando eso y me cuentas, si te sigue tirando error podemos ver otra solución. Adjunto foto con tu código funcionando bien desde mi computador.

Por último un detalle, en tu README tienes el comando:
<pre>
curl -F "url={NGROK_URL}/webhook" "https://api.telegram.org/{BOT_TOKEN}/setWebhook"
</pre>

pero debería ser:
<pre>
curl -F "url={NGROK_URL}/webhook" "https://api.telegram.org/bot{BOT_TOKEN}/setWebhook"
</pre>

![image](https://github.com/IIC2513/Syllabus-S1/assets/89492735/2d21055d-378f-4207-97a2-f930cc15f8c9)

**Comment by tadonisb** [comment]
!! Muchísimas gracias! Parece que algo está pasando con mi computador porque la mayor parte del desarrollo lo he hecho probando en el puerto 3000, pero tampoco me funcionaba, el problema no ha sido el puerto. Sin importar que puerto probaba, el servidor se levantaba bien pero las APIs no lo reconocian como disponible. 

Muchas gracias, voy a seguir trabajando con cuidado esperando que funcione en corrección jajajaj
