### ISSUE TITLE
[T4] Nombre bot en README

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2513/Syllabus-S1-2024-1#86]
Wenas, me acabo de fijar en que no puse el nombre del bot en el README dou

Puedo modificar algo o mandarlo por algún lado o debo esperar alguna instancia de recorrección?

:(

**Comment by nanglada** [comment]
Hola! Mándamelo por correo (natalia.anglada@uc.cl) o por telegram (@natyanglada)
